// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-api-key-here',
    appId: '1:your-project-number:web:your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'pawpal-da2d9',
    authDomain: 'pawpal-da2d9.firebaseapp.com',
    storageBucket: 'pawpal-da2d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: '1:your-project-number:android:your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'pawpal-da2d9',
    storageBucket: 'pawpal-da2d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:your-project-number:ios:your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'pawpal-da2d9',
    storageBucket: 'pawpal-da2d9.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:your-project-number:macos:your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'pawpal-da2d9',
    storageBucket: 'pawpal-da2d9.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:your-project-number:windows:your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'pawpal-da2d9',
    storageBucket: 'pawpal-da2d9.appspot.com',
  );
}